### ISSUE TITLE
No 3x support

### ISSUE THREAD

**Issue by LeoNatan** [krzysztofzablocki/IconOverlaying#26]
Hello, 3x icon variants are not supported currently.

**Comment by EvgenyKarkan** [comment]
For me everything works as expected & app icon on iPhone 6+ has overlay.

**Comment by EvgenyKarkan** [comment]
@LeoNatan could you please update this issue?

**Comment by LeoNatan** [comment]
Does the app have a proper 3x icon? The script, at the time of opening the issue, did not read the 3x variants, only the 2x ones.

**Comment by EvgenyKarkan** [comment]
@LeoNatan Yes, my app has all icons, 3x icon among them. 
It seems that #29 b57ac37b82bbf906e595bfba3cf53d8f3d511bf7 commit fixes this issue. 
Thanks.
