### ISSUE TITLE
iPad handling is bad

### ISSUE THREAD

**Issue by LeoNatan** [krzysztofzablocki/IconOverlaying#27]
The current "fix" for iPad is bad, as it only attempts to fix two hard-coded file names, whereas in real world scenarios, each icon can be different between iPhone and iPad.

Better to use `-c "Print CFBundleIcons~ipad:CFBundlePrimaryIcon:CFBundleIconFiles"` to get iPad icons.

Images can also have `~ipad` prefix, which should also be taken care of. The current "fix" will miss most newer app bundles due to Asset Catalog compiler outputting "AppIcon76x76@2x~ipad.png"

**Comment by EvgenyKarkan** [comment]
@LeoNatan does you solution work?

**Comment by LeoNatan** [comment]
It works, but is not "general availablity" ready. I will post tomorrow my current script.

**Comment by EvgenyKarkan** [comment]
@LeoNatan waiting for it. 
Thanks!

**Comment by EvgenyKarkan** [comment]
Hi guys!
Is any progress on that issue? 
Best wishes.

**Comment by ninokierulf** [comment]
hi guys, found a more flexible fix without hardcoding the workaround for iPad
just replace CFBundleIcons with CFBundleIcons~ipad in the script.

**Comment by krzysztofzablocki** [comment]
seems like that pr fixes it
